### ISSUE TITLE
pod create lib 

### ISSUE THREAD

**Issue by abitofalchemy** [STMicroelectronics/STBLESensor_iOS#1]
I don't know if I'm doing this right: I get this error & I'm unsure how to fix it:
> clang: error: no such file or directory: '/Volumes/theory/SandBox/STBlueMS_iOS/Pods/MQTTClient/MQTTClient/MQTTClient/MQTTCFSocketDecoder.m'
clang: error: no input files

Do I need to execute something else before opening and building the W2STApp.xcodeproj project?

**Comment by GiovanniVisentiniST** [comment]
Yes we use CocoaPods as dependency manager. 
You have to install it and run:
`pod install`
from the project directory, to install the ST BlueMS dependency.
See the [CocoaPods](https://cocoapods.org/) site for more details

**Comment by abitofalchemy** [comment]
Thank you.
