### ISSUE TITLE
OTA not working

### ISSUE THREAD

**Issue by TheAlbertDev** [STMicroelectronics/STBLESensor_iOS#11]
ST Community thread: [https://community.st.com/t5/stm32-mcus-wireless/difference-ota-procedure-stm32cubemonitorrf-vs-st-ble-sensor-app/td-p/638619#M17853](https://community.st.com/t5/stm32-mcus-wireless/difference-ota-procedure-stm32cubemonitorrf-vs-st-ble-sensor-app/td-p/638619#M17853)

Hi! 👋🏻 

I have programmed a STM32WB5MMG with the SBSFU + OTA + User app. The SBSFU is able to start the user app with no problem, and the user app is able to start the OTA app.

The problem comes when starting the update process. With STM32CubeMonitorRF there is no problem: the device is updated to the new version of the user app. However, when the operation is performed with the ST BLE Sensor app (iOS), the image is sent (100%), but the OTA does not restart to install the new user app and the 100% message does not disappear from the mobile app.

With the normal OTA (without SBSU) I have been able to update the versions of the user app with the mobile application.

I've been able to "steal" an Android to a colleague and I've been able to verify that with the Android version OTA works properly. It is the iOS version that does not work.

Thanks for your time.

**Comment by TheAlbertDev** [comment]
Last update on Android version: last month
Last update on iOS version: 8 months ago.

Is this an abandoned project without support?

**Comment by PezzoniL** [comment]
The iOS version will be updated on the next months we had worked on a new Application for both the platforms: Android and iOS and we had no rooms to update also the ST BLE Sensor for iOS
The ST BLE Sensor for Android is more updated

We had found a pb for OTA for WB boards for both ST BLE Sensor and ST BLE Toolbox application for iOS
The same applications for Android are correct

**Comment by TheAlbertDev** [comment]
> The iOS version will be updated on the next months we had worked on a new Application for both the platforms: Android and iOS and we had no rooms to update also the ST BLE Sensor for iOS The ST BLE Sensor for Android is more updated
> 
> We had found a pb for OTA for WB boards for both ST BLE Sensor and ST BLE Toolbox application for iOS The same applications for Android are correct

Thx @PezzoniL for your response and your work. We will be keeping an eye on the new updates/releases.
