### ISSUE TITLE
mRecordData:Data? object what is type is this

### ISSUE THREAD

**Issue by abitofalchemy** [STMicroelectronics/STBLESensor_iOS#2]
Hello,
This is very basic question, what type object is `mRecordData` in `W2STApp/MainApp/Demo/BlueVoice/W2STBlueVoiceViewController.swift`?
 
Is this just a standard NSData object, which is just pointing to some memory values?

**Comment by GiovanniVisentiniST** [comment]
the `mRecordData `is declared as [`Data?`](https://github.com/STMicroelectronics-CentralLabs/STBlueMS_iOS/blob/d3da882d2a70a02ddf944975b43e02dff242bc83/W2STApp/MainApp/Demo/BlueVoice/W2STBlueVoiceViewController.swift#L125)

`Data `is the Swift equivalent type of `NSData`. See [here](https://developer.apple.com/documentation/foundation/data)
