### ISSUE TITLE
Gets a runtime exception breakpoint

### ISSUE THREAD

**Issue by dinukasal** [STMicroelectronics/STBLESensor_iOS#3]
When I compile and run this project it gives this exception as a breakpoint,

```
dyld: Library not loaded: @rpath/Starscream.framework/Starscream
 Referenced from: /private/var/containers/Bundle/Application/F2E5619F-FAD1-4D20-B904-6F9E36D4933F/ST BlueMS.app/Frameworks/SpeechToTextV1.framework/SpeechToTextV1
 Reason: image not found
(lldb)
```
Please help me to fix the issue.

Xcode version 9.2

Thanks

**Comment by GiovanniVisentiniST** [comment]
Hi,

did you install carthage and run:
`carthage update --platform iOS --no-use-binaries` ?

**Comment by dinukasal** [comment]
There was a problem with signing certificates. I had to remove the signing certificates from keychain and then add some dependency libraries from Linked Libraries to Embedded Binaries in Xcode.
