### ISSUE TITLE
Use of unresolved identifier 'AudioMediaType'

### ISSUE THREAD

**Issue by skaterSteve** [STMicroelectronics/STBLESensor_iOS#4]
Hello, 

I am trying to build this example targeting an iOS device.  I have set WSTApp > my iPhone and fixed the provisioning profile issue.  I am using Xcode 9

I saw that an issue said my provisioning profile didn't allow for CloudKit connection, so I signed up for the license so that I can build this project and launch to my phone.  

That issue has gone away now, but now I am seeing that "AudioMediaType" is not defined in the IBMWatsonASREngine.swift file 

The three errors I am currently having are:
Use of unresolved identifier 'AudioMediaType'
  -  it seems missing a definition
Value of optional type '[SpeechRecognitionResult]?' not unwrapped; did you mean to use '!' or '?'? IBMWatsonASREngine.swift
 - could this be due to the undefined 'AudioMediaType' variable?

Thanks.

**Comment by GiovanniVisentiniST** [comment]
Hello,

the Watson library change after the release of this code, and the Cartage file was requesting for the last available version.

I did a commit to request a precise version (v 0.24) that is the last one that is working..

please do a pull and re lunch the command:
`carthage update --platform iOS --no-use-binaries`

to update the library.

Thanks
Giovanni

**Comment by skaterSteve** [comment]
Thank you for the prompt response Giovanni.  That fixed it and project builds successfully!

Best,
Steven
