### ISSUE TITLE
EXC_ BAD_ACCESS

### ISSUE THREAD

**Issue by Baptystes** [STMicroelectronics/STBLESensor_iOS#6]
Hi,
I'm quite a beginner with swift, but the app is well installed on my device with swift 5.1. 
When clicking on "Connect to a device" on the first screen, it leads to a EXC_ BAD_ACCESS.

The error lead to this file : STBlueMS_iOS⁩ ▸ ⁨BlueSTSDK⁩ ▸ ⁨BlueSTSDK⁩ ▸ ⁨BlueSTSDK⁩ ▸ BlueSTSDKManager.swift
 `Line 39 : let  defaultFeatureMap = BlueSTSDKBoardFeatureMap.boardFeatureMap()`

I'm using an iPhone 8 iOS 12.2, Xcode 10.2.1 and Swift 5.1
Could you help me solving the problem ? Thx by advance!

**Comment by cheinig** [comment]
Same problem here on the same environment. Any solution available?
Using iPhone 8 iOS 12.3, Xcode 10.2.1 and Swift 5.1

**Comment by GiovanniVisentiniST** [comment]
Hello,

the problem is this one:
https://github.com/STMicroelectronics/BlueSTSDK_iOS/issues/4

please move the BlueSTSDK reference to the new master.

Thanks
Giovanni

**Comment by cheinig** [comment]
Updating BlueSTSDK_iOS to master branch (commit 16d88d9) without some code changes in the modules BlueSTSDK_iOS and BlueSTSDK_GUI_iOS seems not to work (compiler errors)

With the following changes i was able build and run the app:

Update BlueSTSDK Submodule to current master (last commit at the moment 16d88d9)
```
cd ./BlueSTSDK
git checkout master
```

Modify the files in the following modules
```
Module: BlueSTSDK
File:   ./BlueSTSDK/Util/Advertise/BlueSTSDKAdvertiseInfo.swift
Action: Add "open" access level to class
Action: Add "public" access level to "init"
```

```
Module: BlueSTSDK_GUI
File:   ./BlueNRG/fwUpgrade/BlueNRGOtaAdvertiseParser.swift
Action: Change return type of function "filter" to "BleAdvertiseInfo"
```

```
Module: W2STApp
File:   ./W2STApp/MainApp/Demo/FFTAmplitude/FFTAmplitudeViewController.swift
Action: Change parameter label from "value" to "entries" in line 233
            let line =  LineChartDataSet(entries: data,label: conf.name)
```

Thanks for your help.

**Comment by Baptystes** [comment]
Hi, 
Thank you very much both for your help, it worked!
Have a nice day,
Baptiste
